variables:
  MAVEN_OPTS: "-Xmx1536m"

stages:
  - prepare
  - build
  - test
  - analyze
  - deploy

maven-prepare:
  stage: prepare
  script:
    - "./config-test.py"
  artifacts:
    paths:
      - gitlab-ci.build.conf

.maven-build:
  stage: build
  environment: staging
  script:
    - "mvn -Ptest -DskipTests clean compile"

.maven-test:
  stage: test
  environment: staging
  script:
    - "source gitlab-ci.build.conf"
    - "mvn -Ptest clean test"

.maven-deploy:
  stage: deploy
  environment: staging
  script:
    - "mvn -Ptest deploy -DskipTests -DperformRelease -Ddistribution=igloo-release"
  only:
    - /^master$/
    - /^dev$/
    - /^deploy-.*$/

sonar-analyze:
  stage: analyze
  environment: staging
  script:
    - "source gitlab-ci.build.conf"
    - mvn -Ptest clean verify sonar:sonar
      -DskipTests
      -Dsonar.host.url="https://sonar.tools.kobalt-si.fr"
