variables:
  MAVEN_OPTS: "-Xmx1536m"

stages:
  - prepare
  - build
  - test
  - analyze
  - deploy

maven-prepare:
  stage: prepare
  script:
    - "./config-test.py"
  artifacts:
    paths:
      - gitlab-ci.build.conf

maven-build:
  stage: build
  environment: staging
  script:
    - "mvn -Ptest -DskipTests clean compile"

maven-test:
  stage: test
  environment: staging
  script:
    - "source gitlab-ci.build.conf"
    - "set +e"
    - "mvn -Ptest -Dallure.enabled=true -fae clean test site:site"
    - "TEST_RESULT=$?"
    - "mvn -Dallure.enabled=true site:site"
    - "eval $(ssh-agent -s)"
    - echo "$SYNC_TEST_REPORTS_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SYNC_TEST_REPORTS_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -az --chmod=g=rX,o= target/site/ "${SYNC_TEST_REPORTS_USER}@${SYNC_TEST_REPORTS_HOST}:${SYNC_TEST_REPORTS_DOCUMENT_ROOT}"
    - "exit $TEST_RESULT"
  artifacts:
    paths:
      - target/site/
    when: always

maven-deploy:
  stage: deploy
  environment: staging
  script:
    - "mvn -Ptest deploy -DskipTests -DperformRelease -Ddistribution=igloo-release"
  only:
    - /^master$/
    - /^dev$/
    - /^deploy-.*$/

sonar-analyze:
  stage: analyze
  environment: staging
  script:
    - "source gitlab-ci.build.conf"
    - mvn -Ptest clean verify sonar:sonar
      -DskipTests
      -Dsonar.host.url="https://sonar.tools.kobalt-si.fr"
