variables:
  MAVEN_OPTS: "-Xmx1536m"

stages:
  - prepare
  - build
  - test
  - analyze
  - deploy

maven-prepare:
  stage: prepare
  script:
    - "./ci/config-test.py"
  artifacts:
    expire_in: 1 day
    paths:
      - gitlab-ci.build.conf

maven-build:
  stage: build
  environment: staging
  script:
    - "mvn -DskipTests clean package"

maven-test:
  stage: test
  environment: staging
  artifacts:
    expire_in: 1 day
    paths:
      - artifacts/
  script:
    - "source gitlab-ci.build.conf"
    - "./ci/maven-allure.sh"

maven-deploy:
  stage: deploy
  environment: staging
  script:
    - "mvn deploy -DskipTests -DperformRelease -Ddistribution=igloo-release"
  only:
    - /^master$/
    - /^dev$/
    - /^ft-.*-deploy$/
    - /^rl-.*$/
    - /^hf-.*$/

sonar-analyze:
  stage: analyze
  environment: staging
  script:
    - "source gitlab-ci.build.conf"
    - ./ci/artifacts-pull.sh
    - find -name jacoco.exec
    - mvn verify sonar:sonar
      -DskipTests
      -Dsonar.host.url="https://sonar.tools.kobalt.fr"
      -Dsonar.jacoco.reportPaths=target/jacoco.exec
