variables:
  MAVEN_OPTS: "-Denforcer.skip=true -Xmx2048m"

stages:
  - build
  - test
  - analyze
  - deploy

maven-build:
  stage: build
  environment: staging
  script:
    - "echo $MAVEN_OPTS"
    - "export"
    - "mvn -Ptest -DskipTests clean compile"

maven-test:
  stage: test
  environment: staging
  script:
    - "mvn -Ptest clean test"

maven-deploy:
  stage: deploy
  environment: staging
  script:
    - "mvn -Ptest deploy -DskipTests -DperformRelease -Ddistribution=igloo-release"
  only:
    - /^master$/
    - /^dev$/
    - /^deploy-.*$/

sonar-analyze:
  stage: analyze
  environment: staging
  script:
    - mvn -Ptest clean verify sonar:sonar
      -DskipTests
      -Dsonar.projectKey="$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
      -Dsonar.projectName="$CI_PROJECT_NAME · $CI_COMMIT_REF_NAME"
      -Dsonar.host.url="https://sonar.tools.kobalt-si.fr"
