language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
  apt:
    packages:
      - oracle-java8-installer
install:
  - mvn -v
  - mvn -B -q -Ptest install -DskipTests=true
before_script: 
  - psql -U postgres -f travis/postgresql.sql
script: mvn -U -Ptest clean package
