language: java
jdk:
  - oraclejdk7
addons:
  postgresql: "9.4"
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
install:
  - mvn -v
  - mvn -B -q -Ptravis clean install -DskipTests=true
before_script: 
  - psql -U postgres -f travis/postgresql.sql
script: mvn -U -Ptravis clean package
