language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
install:
  - mvn -B -q install -DskipTests=true
before_script: 
  - psql -U postgres -f travis/postgresql.sql
script: mvn -U -Ptest clean package
